def test_get_all_products(client):
    ...

def test_get_product_by_name(client):
    ...

def test_get_product_by_category(client):
    ...

def test_get_product_by_availability(client):
    ...

def test_update_product(client):
    ...

def test_delete_product(client):
    ...
